spring.application.name=week7embeddings
spring.ai.openai.api-key=${OPENAI_API_KEY:demo}
spring.ai.openai.embedding.options.model=text-embedding-3-small
spring.ai.ollama.chat.options.model=llama3.2:1b
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.options.model=mxbai-embed-large
